version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///dev.db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tests:
    build: .
    command: pytest
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=testing
      - DATABASE_URL=sqlite:///test.db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

volumes:
  redis_data: 