# fly.toml app configuration file generated for dopple503 on 2025-06-03T08:47:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dopple503"
primary_region = "lax"  # Los Angeles, change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"
  HOST = "0.0.0.0"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "1"
  PYTHONPATH = "/app"
  DATABASE_URL = "{{ .Secrets.DATABASE_URL }}"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "15s"
    grace_period = "180s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = true
    headers = { Host = "dopple503.fly.dev" }

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 8192
  memory_gb = 8

[[metrics]]
  port = 9091
  path = "/metrics"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "15s"
    grace_period = "180s"

[mounts]
  source = "dopple_data"
  destination = "/app/data"
  initial_size = "1GB"

[deploy]
  strategy = "rolling"
  max_per_region = 1
  wait_for_health_checks = true
  health_check_timeout = "180s"
