services:
  - type: web
    name: dopp-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        sync: false
      - key: B2_APPLICATION_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: SECRET_KEY
        generateValue: true 