services:
  - type: web
    name: dopp-backend
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: source /opt/venv/bin/activate && gunicorn app:app --workers 2 --threads 2 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: B2_APPLICATION_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
    plan: standard
    buildFilter:
      paths:
        - package.json
        - requirements.txt
        - build.sh
        - app.py
        - render.yaml
    healthCheckPath: /api/health
    autoDeploy: true 